DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(
	USER_ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
	USER_NAME VARCHAR(30) NULL DEFAULT NULL COMMENT '用户名',
	PASSWORD VARCHAR(30) NULL DEFAULT NULL COMMENT '密码',
	EMAIL VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	PHONE VARCHAR(11) NULL DEFAULT NULL COMMENT '手机号',
	FULL_NAME VARCHAR(30) NULL DEFAULT NULL COMMENT '全名',
	PRIMARY KEY (USER_ID)
);